db.registrations.insertMany([{userID: ObjectId('67c7d6da1b9b7f2089893bf8'),
      rollNo: '2025ITEP0001',
      email: 'user1@example.com',
      name: 'User1',
      fatherName: 'FatherName1',
      dob: '2000-01-01',
      localAddress: 'Local Address 1',
      permanentAddress: 'Permanent Address 1',
      gender: 'male',
      contact: '1231231200',
      maritalStatus: 'unmarried',
      qualification: "Bachelor's Degree",
      annualIncome: '3-6L',
      preferredCity: 'Indore',
      reference: 'LinkedIn',
      passportPhoto: 'http://localhost:3001/userDoc/image.png',
      marksheet12: 'http://localhost:3001/userDoc/image.png',
      latestMarksheet: 'http://localhost:3001/userDoc/image.png',
      aadhar: 'http://localhost:3001/userDoc/image.png',
      fatherAadhar: 'http://localhost:3001/userDoc/image.png',
      samagraId: 'http://localhost:3001/userDoc/image.png',
      incomeCertificate: 'http://localhost:3001/userDoc/image.png',
      transactionId: 'DummyId',
      courseType: 'ITEP',
      isVerified: 'Pending'
    },
    {
      userID: ObjectId('67c7d6da1b9b7f2089893bf9'),
      rollNo: '2025BREP0001',
      email: 'user2@example.com',
      name: 'User2',
      fatherName: 'FatherName2',
      dob: '1999-05-12',
      localAddress: 'Local Address 2',
      permanentAddress: 'Permanent Address 2',
      gender: 'female',
      contact: '1231231201',
      maritalStatus: 'married',
      qualification: "Master's Degree",
      annualIncome: '6-10L',
      preferredCity: 'Pune',
      reference: 'Instagram',
      passportPhoto: 'http://localhost:3001/userDoc/image.png',
      marksheet12: 'http://localhost:3001/userDoc/image.png',
      latestMarksheet: 'http://localhost:3001/userDoc/image.png',
      aadhar: 'http://localhost:3001/userDoc/image.png',
      fatherAadhar: 'http://localhost:3001/userDoc/image.png',
      samagraId: 'http://localhost:3001/userDoc/image.png',
      incomeCertificate: 'http://localhost:3001/userDoc/image.png',
      transactionId: 'DummyId',
      courseType: 'BREP',
      isVerified: 'Pending'
    },
    {
      userID: ObjectId('67c7d6da1b9b7f2089893bfa'),
      rollNo: '2025ITEP0002',
      email: 'user3@example.com',
      name: 'User3',
      fatherName: 'FatherName3',
      dob: '1998-03-15',
      localAddress: 'Local Address 3',
      permanentAddress: 'Permanent Address 3',
      gender: 'male',
      contact: '1231231202',
      maritalStatus: 'unmarried',
      qualification: 'Diploma',
      annualIncome: '0-3L',
      preferredCity: 'Indore',
      reference: 'Facebook',
      passportPhoto: 'http://localhost:3001/userDoc/image.png',
      marksheet12: 'http://localhost:3001/userDoc/image.png',
      latestMarksheet: 'http://localhost:3001/userDoc/image.png',
      aadhar: 'http://localhost:3001/userDoc/image.png',
      fatherAadhar: 'http://localhost:3001/userDoc/image.png',
      samagraId: 'http://localhost:3001/userDoc/image.png',
      incomeCertificate: 'http://localhost:3001/userDoc/image.png',
      transactionId: 'DummyId',
      courseType: 'ITEP',
      isVerified: 'Pending'
    },
    {
      userID: ObjectId('67c7d6da1b9b7f2089893bfb'),
      rollNo: '2025BREP0002',
      email: 'user4@example.com',
      name: 'User4',
      fatherName: 'FatherName4',
      dob: '2000-07-18',
      localAddress: 'Local Address 4',
      permanentAddress: 'Permanent Address 4',
      gender: 'female',
      contact: '1231231203',
      maritalStatus: 'married',
      qualification: "Bachelor's Degree",
      annualIncome: '10-15L',
      preferredCity: 'Pune',
      reference: 'Print Media',
      passportPhoto: 'http://localhost:3001/userDoc/image.png',
      marksheet12: 'http://localhost:3001/userDoc/image.png',
      latestMarksheet: 'http://localhost:3001/userDoc/image.png',
      aadhar: 'http://localhost:3001/userDoc/image.png',
      fatherAadhar: 'http://localhost:3001/userDoc/image.png',
      samagraId: 'http://localhost:3001/userDoc/image.png',
      incomeCertificate: 'http://localhost:3001/userDoc/image.png',
      transactionId: 'DummyId',
      courseType: 'BREP',
      isVerified: 'Pending'
    },
    {
      userID: ObjectId('67c7d6da1b9b7f2089893bfc'),
      rollNo: '2025ITEP0003',
      email: 'user5@example.com',
      name: 'User5',
      fatherName: 'FatherName5',
      dob: '1997-12-22',
      localAddress: 'Local Address 5',
      permanentAddress: 'Permanent Address 5',
      gender: 'male',
      contact: '1231231204',
      maritalStatus: 'unmarried',
      qualification: "Master's Degree",
      annualIncome: 'More Than 15 LPA',
      preferredCity: 'Indore',
      reference: 'Other',
      passportPhoto: 'http://localhost:3001/userDoc/image.png',
      marksheet12: 'http://localhost:3001/userDoc/image.png',
      latestMarksheet: 'http://localhost:3001/userDoc/image.png',
      aadhar: 'http://localhost:3001/userDoc/image.png',
      fatherAadhar: 'http://localhost:3001/userDoc/image.png',
      samagraId: 'http://localhost:3001/userDoc/image.png',
      incomeCertificate: 'http://localhost:3001/userDoc/image.png',
      transactionId: 'DummyId',
      courseType: 'ITEP',
      isVerified: 'Pending'
    },
    {
      userID: ObjectId('67c7d6da1b9b7f2089893bfd'),
      rollNo: '2025BREP0003',
      email: 'user6@example.com',
      name: 'User6',
      fatherName: 'FatherName6',
      dob: '2001-11-02',
      localAddress: 'Local Address 6',
      permanentAddress: 'Permanent Address 6',
      gender: 'female',
      contact: '1231231205',
      maritalStatus: 'married',
      qualification: 'Diploma',
      annualIncome: '3-6L',
      preferredCity: 'Pune',
      reference: 'LinkedIn',
      passportPhoto: 'http://localhost:3001/userDoc/image.png',
      marksheet12: 'http://localhost:3001/userDoc/image.png',
      latestMarksheet: 'http://localhost:3001/userDoc/image.png',
      aadhar: 'http://localhost:3001/userDoc/image.png',
      fatherAadhar: 'http://localhost:3001/userDoc/image.png',
      samagraId: 'http://localhost:3001/userDoc/image.png',
      incomeCertificate: 'http://localhost:3001/userDoc/image.png',
      transactionId: 'DummyId',
      courseType: 'BREP',
      isVerified: 'Pending'
    },
    {
      userID: ObjectId('67c7d6da1b9b7f2089893bfe'),
      rollNo: '2025ITEP0004',
      email: 'user7@example.com',
      name: 'User7',
      fatherName: 'FatherName7',
      dob: '1999-09-09',
      localAddress: 'Local Address 7',
      permanentAddress: 'Permanent Address 7',
      gender: 'male',
      contact: '1231231206',
      maritalStatus: 'unmarried',
      qualification: "Bachelor's Degree",
      annualIncome: '6-10L',
      preferredCity: 'Indore',
      reference: 'Instagram',
      passportPhoto: 'http://localhost:3001/userDoc/image.png',
      marksheet12: 'http://localhost:3001/userDoc/image.png',
      latestMarksheet: 'http://localhost:3001/userDoc/image.png',
      aadhar: 'http://localhost:3001/userDoc/image.png',
      fatherAadhar: 'http://localhost:3001/userDoc/image.png',
      samagraId: 'http://localhost:3001/userDoc/image.png',
      incomeCertificate: 'http://localhost:3001/userDoc/image.png',
      transactionId: 'DummyId',
      courseType: 'ITEP',
      isVerified: 'Pending'
    },
    {
      userID: ObjectId('67c7d6da1b9b7f2089893bff'),
      rollNo: '2025BREP0004',
      email: 'user8@example.com',
      name: 'User8',
      fatherName: 'FatherName8',
      dob: '2000-04-04',
      localAddress: 'Local Address 8',
      permanentAddress: 'Permanent Address 8',
      gender: 'female',
      contact: '1231231207',
      maritalStatus: 'married',
      qualification: "Master's Degree",
      annualIncome: '0-3L',
      preferredCity: 'Pune',
      reference: 'Facebook',
      passportPhoto: 'http://localhost:3001/userDoc/image.png',
      marksheet12: 'http://localhost:3001/userDoc/image.png',
      latestMarksheet: 'http://localhost:3001/userDoc/image.png',
      aadhar: 'http://localhost:3001/userDoc/image.png',
      fatherAadhar: 'http://localhost:3001/userDoc/image.png',
      samagraId: 'http://localhost:3001/userDoc/image.png',
      incomeCertificate: 'http://localhost:3001/userDoc/image.png',
      transactionId: 'DummyId',
      courseType: 'BREP',
      isVerified: 'Pending'
    },
    {
      userID: ObjectId('67c7d6da1b9b7f2089893c00'),
      rollNo: '2025ITEP0005',
      email: 'user9@example.com',
      name: 'User9',
      fatherName: 'FatherName9',
      dob: '1998-02-20',
      localAddress: 'Local Address 9',
      permanentAddress: 'Permanent Address 9',
      gender: 'male',
      contact: '1231231208',
      maritalStatus: 'unmarried',
      qualification: 'Diploma',
      annualIncome: '10-15L',
      preferredCity: 'Indore',
      reference: 'Print Media',
      passportPhoto: 'http://localhost:3001/userDoc/image.png',
      marksheet12: 'http://localhost:3001/userDoc/image.png',
      latestMarksheet: 'http://localhost:3001/userDoc/image.png',
      aadhar: 'http://localhost:3001/userDoc/image.png',
      fatherAadhar: 'http://localhost:3001/userDoc/image.png',
      samagraId: 'http://localhost:3001/userDoc/image.png',
      incomeCertificate: 'http://localhost:3001/userDoc/image.png',
      transactionId: 'DummyId',
      courseType: 'ITEP',
      isVerified: 'Pending'
    },
    {
      userID: ObjectId('67c7d6da1b9b7f2089893c01'),
      rollNo: '2025BREP0005',
      email: 'user10@example.com',
      name: 'User10',
      fatherName: 'FatherName10',
      dob: '2001-06-30',
      localAddress: 'Local Address 10',
      permanentAddress: 'Permanent Address 10',
      gender: 'female',
      contact: '1231231209',
      maritalStatus: 'married',
      qualification: "Bachelor's Degree",
      annualIncome: 'More Than 15 LPA',
      preferredCity: 'Pune',
      reference: 'Other',
      passportPhoto: 'http://localhost:3001/userDoc/image.png',
      marksheet12: 'http://localhost:3001/userDoc/image.png',
      latestMarksheet: 'http://localhost:3001/userDoc/image.png',
      aadhar: 'http://localhost:3001/userDoc/image.png',
      fatherAadhar: 'http://localhost:3001/userDoc/image.png',
      samagraId: 'http://localhost:3001/userDoc/image.png',
      incomeCertificate: 'http://localhost:3001/userDoc/image.png',
      transactionId: 'DummyId',
      courseType: 'BREP',
      isVerified: 'Pending'
    },
    {
      userID: ObjectId('67c7d6da1b9b7f2089893c02'),
      rollNo: '2025ITEP0006',
      email: 'user11@example.com',
      name: 'User11',
      fatherName: 'FatherName11',
      dob: '1997-08-16',
      localAddress: 'Local Address 11',
      permanentAddress: 'Permanent Address 11',
      gender: 'male',
      contact: '1231231210',
      maritalStatus: 'unmarried',
      qualification: "Master's Degree",
      annualIncome: '3-6L',
      preferredCity: 'Indore',
      reference: 'LinkedIn',
      passportPhoto: 'http://localhost:3001/userDoc/image.png',
      marksheet12: 'http://localhost:3001/userDoc/image.png',
      latestMarksheet: 'http://localhost:3001/userDoc/image.png',
      aadhar: 'http://localhost:3001/userDoc/image.png',
      fatherAadhar: 'http://localhost:3001/userDoc/image.png',
      samagraId: 'http://localhost:3001/userDoc/image.png',
      incomeCertificate: 'http://localhost:3001/userDoc/image.png',
      transactionId: 'DummyId',
      courseType: 'ITEP',
      isVerified: 'Pending'
    },
    {
      userID: ObjectId('67c7d6da1b9b7f2089893c03'),
      rollNo: '2025BREP0006',
      email: 'user12@example.com',
      name: 'User12',
      fatherName: 'FatherName12',
      dob: '1999-10-10',
      localAddress: 'Local Address 12',
      permanentAddress: 'Permanent Address 12',
      gender: 'female',
      contact: '1231231211',
      maritalStatus: 'married',
      qualification: 'Diploma',
      annualIncome: '6-10L',
      preferredCity: 'Pune',
      reference: 'Facebook',
      passportPhoto: 'http://localhost:3001/userDoc/image.png',
      marksheet12: 'http://localhost:3001/userDoc/image.png',
      latestMarksheet: 'http://localhost:3001/userDoc/image.png',
      aadhar: 'http://localhost:3001/userDoc/image.png',
      fatherAadhar: 'http://localhost:3001/userDoc/image.png',
      samagraId: 'http://localhost:3001/userDoc/image.png',
      incomeCertificate: 'http://localhost:3001/userDoc/image.png',
      transactionId: 'DummyId',
      courseType: 'BREP',
      isVerified: 'Pending'
    },
    {
      userID: ObjectId('67c7d6da1b9b7f2089893c04'),
      rollNo: '2025ITEP0007',
      email: 'user13@example.com',
      name: 'User13',
      fatherName: 'FatherName13',
      dob: '2000-03-03',
      localAddress: 'Local Address 13',
      permanentAddress: 'Permanent Address 13',
      gender: 'male',
      contact: '1231231212',
      maritalStatus: 'unmarried',
      qualification: "Bachelor's Degree",
      annualIncome: '0-3L',
      preferredCity: 'Indore',
      reference: 'Instagram',
      passportPhoto: 'http://localhost:3001/userDoc/image.png',
      marksheet12: 'http://localhost:3001/userDoc/image.png',
      latestMarksheet: 'http://localhost:3001/userDoc/image.png',
      aadhar: 'http://localhost:3001/userDoc/image.png',
      fatherAadhar: 'http://localhost:3001/userDoc/image.png',
      samagraId: 'http://localhost:3001/userDoc/image.png',
      incomeCertificate: 'http://localhost:3001/userDoc/image.png',
      transactionId: 'DummyId',
      courseType: 'ITEP',
      isVerified: 'Pending'
    },
    {
      userID: ObjectId('67c7d6da1b9b7f2089893c05'),
      rollNo: '2025BREP0007',
      email: 'user14@example.com',
      name: 'User14',
      fatherName: 'FatherName14',
      dob: '1998-11-11',
      localAddress: 'Local Address 14',
      permanentAddress: 'Permanent Address 14',
      gender: 'female',
      contact: '1231231213',
      maritalStatus: 'married',
      qualification: "Master's Degree",
      annualIncome: '10-15L',
      preferredCity: 'Pune',
      reference: 'Print Media',
      passportPhoto: 'http://localhost:3001/userDoc/image.png',
      marksheet12: 'http://localhost:3001/userDoc/image.png',
      latestMarksheet: 'http://localhost:3001/userDoc/image.png',
      aadhar: 'http://localhost:3001/userDoc/image.png',
      fatherAadhar: 'http://localhost:3001/userDoc/image.png',
      samagraId: 'http://localhost:3001/userDoc/image.png',
      incomeCertificate: 'http://localhost:3001/userDoc/image.png',
      transactionId: 'DummyId',
      courseType: 'BREP',
      isVerified: 'Pending'
    },
    {
      userID: ObjectId('67c7d6da1b9b7f2089893c06'),
      rollNo: '2025ITEP0008',
      email: 'user15@example.com',
      name: 'User15',
      fatherName: 'FatherName15',
      dob: '1997-07-07',
      localAddress: 'Local Address 15',
      permanentAddress: 'Permanent Address 15',
      gender: 'male',
      contact: '1231231214',
      maritalStatus: 'unmarried',
      qualification: 'Diploma',
      annualIncome: 'More Than 15 LPA',
      preferredCity: 'Indore',
      reference: 'Other',
      passportPhoto: 'http://localhost:3001/userDoc/image.png',
      marksheet12: 'http://localhost:3001/userDoc/image.png',
      latestMarksheet: 'http://localhost:3001/userDoc/image.png',
      aadhar: 'http://localhost:3001/userDoc/image.png',
      fatherAadhar: 'http://localhost:3001/userDoc/image.png',
      samagraId: 'http://localhost:3001/userDoc/image.png',
      incomeCertificate: 'http://localhost:3001/userDoc/image.png',
      transactionId: 'DummyId',
      courseType: 'ITEP',
      isVerified: 'Pending'
    },
    {
      userID: ObjectId('67c7d6da1b9b7f2089893c07'),
      rollNo: '2025BREP0008',
      email: 'user16@example.com',
      name: 'User16',
      fatherName: 'FatherName16',
      dob: '2001-12-12',
      localAddress: 'Local Address 16',
      permanentAddress: 'Permanent Address 16',
      gender: 'female',
      contact: '1231231215',
      maritalStatus: 'married',
      qualification: "Bachelor's Degree",
      annualIncome: '3-6L',
      preferredCity: 'Pune',
      reference: 'LinkedIn',
      passportPhoto: 'http://localhost:3001/userDoc/image.png',
      marksheet12: 'http://localhost:3001/userDoc/image.png',
      latestMarksheet: 'http://localhost:3001/userDoc/image.png',
      aadhar: 'http://localhost:3001/userDoc/image.png',
      fatherAadhar: 'http://localhost:3001/userDoc/image.png',
      samagraId: 'http://localhost:3001/userDoc/image.png',
      incomeCertificate: 'http://localhost:3001/userDoc/image.png',
      transactionId: 'DummyId',
      courseType: 'BREP',
      isVerified: 'Pending'
    },
    {
      userID: ObjectId('67c7d6da1b9b7f2089893c08'),
      rollNo: '2025ITEP0009',
      email: 'user17@example.com',
      name: 'User17',
      fatherName: 'FatherName17',
      dob: '1999-01-25',
      localAddress: 'Local Address 17',
      permanentAddress: 'Permanent Address 17',
      gender: 'male',
      contact: '1231231216',
      maritalStatus: 'unmarried',
      qualification: "Master's Degree",
      annualIncome: '6-10L',
      preferredCity: 'Indore',
      reference: 'Instagram',
      passportPhoto: 'http://localhost:3001/userDoc/image.png',
      marksheet12: 'http://localhost:3001/userDoc/image.png',
      latestMarksheet: 'http://localhost:3001/userDoc/image.png',
      aadhar: 'http://localhost:3001/userDoc/image.png',
      fatherAadhar: 'http://localhost:3001/userDoc/image.png',
      samagraId: 'http://localhost:3001/userDoc/image.png',
      incomeCertificate: 'http://localhost:3001/userDoc/image.png',
      transactionId: 'DummyId',
      courseType: 'ITEP',
      isVerified: 'Pending'
    },
    {
      userID: ObjectId('67c7d6da1b9b7f2089893c09'),
      rollNo: '2025BREP0009',
      email: 'user18@example.com',
      name: 'User18',
      fatherName: 'FatherName18',
      dob: '2000-05-05',
      localAddress: 'Local Address 18',
      permanentAddress: 'Permanent Address 18',
      gender: 'female',
      contact: '1231231217',
      maritalStatus: 'married',
      qualification: 'Diploma',
      annualIncome: '0-3L',
      preferredCity: 'Pune',
      reference: 'Facebook',
      passportPhoto: 'http://localhost:3001/userDoc/image.png',
      marksheet12: 'http://localhost:3001/userDoc/image.png',
      latestMarksheet: 'http://localhost:3001/userDoc/image.png',
      aadhar: 'http://localhost:3001/userDoc/image.png',
      fatherAadhar: 'http://localhost:3001/userDoc/image.png',
      samagraId: 'http://localhost:3001/userDoc/image.png',
      incomeCertificate: 'http://localhost:3001/userDoc/image.png',
      transactionId: 'DummyId',
      courseType: 'BREP',
      isVerified: 'Pending'
    },
    {
      userID: ObjectId('67c7d6da1b9b7f2089893c0a'),
      rollNo: '2025ITEP0010',
      email: 'user19@example.com',
      name: 'User19',
      fatherName: 'FatherName19',
      dob: '1998-08-08',
      localAddress: 'Local Address 19',
      permanentAddress: 'Permanent Address 19',
      gender: 'male',
      contact: '1231231218',
      maritalStatus: 'unmarried',
      qualification: "Bachelor's Degree",
      annualIncome: '10-15L',
      preferredCity: 'Indore',
      reference: 'Print Media',
      passportPhoto: 'http://localhost:3001/userDoc/image.png',
      marksheet12: 'http://localhost:3001/userDoc/image.png',
      latestMarksheet: 'http://localhost:3001/userDoc/image.png',
      aadhar: 'http://localhost:3001/userDoc/image.png',
      fatherAadhar: 'http://localhost:3001/userDoc/image.png',
      samagraId: 'http://localhost:3001/userDoc/image.png',
      incomeCertificate: 'http://localhost:3001/userDoc/image.png',
      transactionId: 'DummyId',
      courseType: 'ITEP',
      isVerified: 'Pending'
    },
    {
      userID: ObjectId('67c7d6da1b9b7f2089893c0b'),
      rollNo: '2025BREP0010',
      email: 'user20@example.com',
      name: 'User20',
      fatherName: 'FatherName20',
      dob: '2001-02-02',
      localAddress: 'Local Address 20',
      permanentAddress: 'Permanent Address 20',
      gender: 'female',
      contact: '1231231219',
      maritalStatus: 'married',
      qualification: "Master's Degree",
      annualIncome: 'More Than 15 LPA',
      preferredCity: 'Pune',
      reference: 'Other',
      passportPhoto: 'http://localhost:3001/userDoc/image.png',
      marksheet12: 'http://localhost:3001/userDoc/image.png',
      latestMarksheet: 'http://localhost:3001/userDoc/image.png',
      aadhar: 'http://localhost:3001/userDoc/image.png',
      fatherAadhar: 'http://localhost:3001/userDoc/image.png',
      samagraId: 'http://localhost:3001/userDoc/image.png',
      incomeCertificate: 'http://localhost:3001/userDoc/image.png',
      transactionId: 'DummyId',
      courseType: 'BREP',
      isVerified: 'Pending'}]);